[workspace]
authors = ["Thomas Wiecki <thomas.wiecki@gmail.com>"]
channels = ["conda-forge"]
name = "ASI-Arch"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pymc = ">=5.25.1,<6"
arviz = ">=0.22.0,<0.23"
pandas = ">=2.3.1,<3"
numpy = ">=2.3.2,<3"
openai = ">=1.98.0,<2"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.7.1,<2"
matplotlib = ">=3.10.5,<4"
